### PR TITLE
goblas: fix Ddot for unaligned slices

### LINKED ISSUE #77: Dgemm unexpected fault
The inner loop of the dgemmSerialNotTrans function is 
````
var tmp float64
for l, v := range b.data[j*b.stride : j*b.stride+b.cols] {
    tmp += atmp[l] * v
}
````
I tried replacing this with 
````
tmp := ddotUnitary(atmp, b.data[j*b.stride : j*b.stride+b.cols])
````
But I got the following panic:
````
brendan:~/Documents/mygo/src/github.com/gonum/blas/goblas$ go test -bench BenchmarkDgemm
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x89aa5]

goroutine 34 [running]:
runtime.gothrow(0x203890, 0x5)
	/Users/brendan/gover/go_1_4_0/src/runtime/panic.go:503 +0x8e fp=0x2083b3590 sp=0x2083b3578
runtime.sigpanic()
	/Users/brendan/gover/go_1_4_0/src/runtime/sigpanic_unix.go:29 +0x261 fp=0x2083b35e0 sp=0x2083b3590
github.com/gonum/blas/goblas.ddotUnitary(0x2083c4840, 0x3, 0xc, 0x2083b5e18, 0x3, 0x3, 0x403d000000000000, 0x1, 0x0, 0x2083ead00, ...)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/goblas/ddot_amd64.s:61 +0x25 fp=0x2083b35e8 sp=0x2083b35e0
github.com/gonum/blas/goblas.dgemmSerialNotTrans(0x2083c4840, 0xc, 0xc, 0x4, 0x3, 0x3, 0x2083b5e00, 0x6, 0x6, 0x2, ...)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/goblas/dgemm.go:378 +0x1f5 fp=0x2083b3680 sp=0x2083b35e8
github.com/gonum/blas/goblas.dgemmSerial(0x6f, 0x70, 0x2083c4840, 0xc, 0xc, 0x4, 0x3, 0x3, 0x2083b5e00, 0x6, ...)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/goblas/dgemm.go:281 +0x16e fp=0x2083b3730 sp=0x2083b3680
github.com/gonum/blas/goblas.dgemmParallel(0x6f, 0x70, 0x2083c4840, 0xc, 0xc, 0x4, 0x3, 0x3, 0x2083b5e00, 0x6, ...)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/goblas/dgemm.go:142 +0x295 fp=0x2083b3880 sp=0x2083b3730
github.com/gonum/blas/goblas.Blas.Dgemm(0x6f, 0x70, 0x4, 0x2, 0x3, 0x4000000000000000, 0x2083c4840, 0xc, 0xc, 0x3, ...)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/goblas/dgemm.go:103 +0x447 fp=0x2083b3a10 sp=0x2083b3880
github.com/gonum/blas/goblas.(*Blas).Dgemm(0x30f0c8, 0x6f, 0x70, 0x4, 0x2, 0x3, 0x4000000000000000, 0x2083c4840, 0xc, 0xc, ...)
	<autogenerated>:9 +0x1b0 fp=0x2083b3ab0 sp=0x2083b3a10
github.com/gonum/blas/testblas.dgemmcomp(0x1, 0x20bf30, 0xe, 0x2083de240, 0x220838c458, 0x30f0c8, 0x6f, 0x70, 0x4, 0x2, ...)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/testblas/dgemm.go:239 +0x36b fp=0x2083b3cb8 sp=0x2083b3ab0
github.com/gonum/blas/testblas.TestDgemm(0x2083de240, 0x220838c458, 0x30f0c8)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/testblas/dgemm.go:218 +0x456 fp=0x2083b3f40 sp=0x2083b3cb8
github.com/gonum/blas/goblas.TestDgemm(0x2083de240)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/goblas/level3double_test.go:10 +0x70 fp=0x2083b3f78 sp=0x2083b3f40
testing.tRunner(0x2083de240, 0x302f98)
	/Users/brendan/gover/go_1_4_0/src/testing/testing.go:447 +0xbf fp=0x2083b3fd0 sp=0x2083b3f78
runtime.goexit()
	/Users/brendan/gover/go_1_4_0/src/runtime/asm_amd64.s:2232 +0x1 fp=0x2083b3fd8 sp=0x2083b3fd0
created by testing.RunTests
	/Users/brendan/gover/go_1_4_0/src/testing/testing.go:555 +0xa8b
````

@fhs -- do you know what's wrong?

### PR DESCRIPTION
**Pull request by fhs**
No real change in the benchmark results
(Go 1.4 on Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz):
```
benchmark                          old ns/op     new ns/op     delta
BenchmarkDdotSmallBothUnitary      15.3          15.3          +0.00%
BenchmarkDdotSmallIncUni           21.5          21.5          +0.00%
BenchmarkDdotSmallUniInc           22.0          22.0          +0.00%
BenchmarkDdotSmallBothInc          21.5          21.5          +0.00%
BenchmarkDdotMediumBothUnitary     505           505           +0.00%
BenchmarkDdotMediumIncUni          1186          1188          +0.17%
BenchmarkDdotMediumUniInc          1178          1178          +0.00%
BenchmarkDdotMediumBothInc         1220          1213          -0.57%
BenchmarkDdotLargeBothUnitary      59322         59327         +0.01%
BenchmarkDdotLargeIncUni           163780        163693        -0.05%
BenchmarkDdotLargeUniInc           141651        141706        +0.04%
BenchmarkDdotLargeBothInc          203541        203794        +0.12%
BenchmarkDdotHugeBothUnitary       9586039       9586340       +0.00%
BenchmarkDdotHugeIncUni            31228460      31128999      -0.32%
BenchmarkDdotHugeUniInc            21437424      21476630      +0.18%
BenchmarkDdotHugeBothInc           40115032      40122703      +0.02%
```
Fixes #77

### CODE REVIEW

File: testblas/level1double.go [hunk 1]
```diff
@@ -1086,6 +1086,12 @@ func DdotTest(t *testing.T, d Ddotter) {
 			t.Errorf("ddot: mismatch %v: expected %v, found %v", c.Name, c.DdotAns, dot)
 		}
 	}
+
```
Comment (btracey) [inline testblas/level1double.go]: Should we add an extra test for this with incremented code as well?

**Comment by btracey** [comment]
LGTM

Would you mean explaining a bit for my education? I tried googling but the discussions were pretty technical. I can see the affect of the change, and understand the differences. However, it seems like there are two instructions that are equally fast, where one only works on aligned data, and the other works on any data. Why would one want to use MOVAPD when you could use MOVUPD instead? Is there a theoretic speed penalty? Is it just that you didn't understand? I'm not trying to be accusatory, just trying to keep up on top of code development. Thanks for the changes.

**Comment by btracey** [comment]
Just a note, early merge because it fixes ddot.We should still consider the incremented test if appropropriate.

**Comment by fhs** [comment]
MODAPD is suppose to be faster than MOVUPD, but in practice, at least on the CPU I ran the benchmarks on, it doesn't make much difference. It general alignment is a good thing. See: https://groups.google.com/d/msg/golang-nuts/HFjwPFYrCqg/oSttxY8ajr4J

File: testblas/level1double.go (hunk 1 above)
Comment (fhs) [inline testblas/level1double.go]: Incremented code doesn't depend on alignment, but I'll the test. Doesn't hurt to have more tests.

**Comment by btracey** [comment]
I'm going to leave a related note on that thread for future readers. Feel free to chime in if you have things to add.

Thanks for the fix.
